Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -8,7 +8,7 @@ on:
 
 jobs:
   build:
-    name: Build and Test default scheme using any available iPhone simulator
+    name: Build and Test VehicleCompanionDebug scheme using any available iPhone simulator
     runs-on: macos-latest
 
     steps:
@@ -17,22 +17,21 @@ jobs:
 
       - name: Set Default Scheme
         run: |
-          # Get the list of schemes and find the default one
-          scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo "Using default scheme: $default"
-          echo $default > default
+          echo "Setting the scheme to VehicleCompanionDebug"
+          echo "VehicleCompanionDebug" > default
+          echo "Using scheme: VehicleCompanionDebug"
 
       - name: Debugging Build Files
         run: |
           echo "Looking for .xcworkspace or .xcodeproj files"
-          ls -A | grep -i \.xcworkspace$
-          ls -A | grep -i \.xcodeproj$
+          # Do not fail if no files are found
+          ls -A | grep -i \.xcworkspace$ || true
+          ls -A | grep -i \.xcodeproj$ || true
 
       - name: Build
         env:
-          scheme: ${{ 'default' }}
-          platform: ${{ 'iOS Simulator' }}
+          scheme: VehicleCompanionDebug
+          platform: iOS Simulator
         run: |
           set -e  # Exit immediately on error
 
@@ -41,9 +40,7 @@ jobs:
           echo "Using device: $device"
 
           # Ensure scheme is set correctly
-          if [ "$scheme" = "default" ]; then
-            scheme=$(cat default)
-          fi
+          scheme=$scheme
           echo "Building with scheme: $scheme"
 
           # Detect workspace or project
@@ -69,8 +66,8 @@ jobs:
 
       - name: Test
         env:
-          scheme: ${{ 'default' }}
-          platform: ${{ 'iOS Simulator' }}
+          scheme: VehicleCompanionDebug
+          platform: iOS Simulator
         run: |
           set -e  # Exit immediately on error
 
@@ -79,9 +76,7 @@ jobs:
           echo "Using device: $device"
 
           # Ensure scheme is set correctly
-          if [ "$scheme" = "default" ]; then
-            scheme=$(cat default)
-          fi
+          scheme=$scheme
           echo "Testing with scheme: $scheme"
 
           # Detect workspace or project
